[package]
name = "hello-compute"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck   = { version = "1.16", features = [ "derive" ] }
env_logger = "0.10"
log        = "0.4"
pollster   = "0.4.0"
wgpu       = "25.0"